name: dart_triage_updater
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-39.0.dev

dependencies:
  args: ^2.4.2
  github: ^9.15.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
