name: Health
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    uses: mosuem/ecosystem/.github/workflows/health.yaml@main
    with:
      coverage_web: false
      upload_coverage: false
    permissions:
      pull-requests: write