# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: Update database
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 14 * * 1-5' # Every workday at 14:00 UTC
    - cron: '0 0 * * 0' # Once a week, at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Update issues and pull requests
        if: github.event.schedule != '0 0 * * 0'
        run: dart run bin/dart_triage_updater.dart --update issues,pullrequests --api-key=${{ secrets.GITHUB_TOKEN }}

      - name: Update googlers
        if: github.event.schedule != '0 14 * * 1-5'
        run: dart run bin/dart_triage_updater.dart --update googlers --api-key=${{ secrets.GITHUB_TOKEN }}
